services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www # problem: для прода не пойдет. Ты в Dockerfile копируешь все файлы в образ, но тут ты монтируешь код снова
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - task-manager-network
    depends_on:
      - db
      - redis
      - ollama

  nginx:
    image: nginx:alpine
    container_name: task-manager-nginx
    restart: unless-stopped
    ports:
      - "8080:80" # problem: 443 пора не хватает
    volumes:
      - ./:/var/www # problem: зачем тут все снова копировать?
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - task-manager-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: task-manager-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager # problem: нужно вынести в .env
      POSTGRES_USER: task_user # problem: нужно вынести в .env
      POSTGRES_PASSWORD: task_password # problem: нужно вынести в .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - task-manager-network

    # problem: healthchecks ?

  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - task-manager-network

  ollama:
    image: ollama/ollama:latest
    container_name: task-manager-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - task-manager-network
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  task-manager-network:
    driver: bridge
